@baseUrl=http://localhost:8080

### Create a new Author
# @name createAuthor
POST {{baseUrl}}/autores
Content-Type: application/json

{
    "nome": "Abobora a",
    "nacionalidade": "Brasileira",
    "dataNascimento": "1990-01-01"
}

@authorId = {{createAuthor.response.body.id}}

### Get the response.id from the previous request
# @name getAuthor
GET {{baseUrl}}/autores/{{authorId}}
Content-Type: application/json

### update Author
# @name updateAuthor
PUT {{baseUrl}}/autores/{{authorId}}
Content-Type: application/json

{
    "nome": "pasdfdsa a",
    "nacionalidade": "asdfasdf",
    "dataNascimento": "1990-01-01"
}

### Search authors
# @name searchAuthor
GET {{baseUrl}}/autores?nome=Abobora
Content-Type: application/json


### Delete Author
# @name deleteAuthor
DELETE  {{baseUrl}}/autores/{{authorId}}
Content-Type: application/json
