@baseUrl=http://localhost:8080

@userPassword = "cc99e988-e004-40ee-8c15-5d9e10685d15"


### Create a new user
# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json

{
    "login": "aaa",
    "password": "123123123",
    "roles": ["Pumpkin"]
}

### Create a new Author
# @name createAuthor
POST {{baseUrl}}/autores
Content-Type: application/json
Authorization: Basic gus:123123123

{
    "nome": "eeeee",
    "nacionalidade": "1232133",
    "dataNascimento": "2020-01-01"
}

@authorId = {{createAuthor.response.body.id}}

### Get the response.id from the previous request
# @name getAuthor
GET {{baseUrl}}/autores/{{authorId}}
Authorization: Basic user:123123123
Content-Type: application/json

### update Author
# @name updateAuthor
PUT {{baseUrl}}/autores/{{authorId}}
Content-Type: application/json

{
    "nome": "ggggg a",
    "nacionalidade": "asdfasdf",
    "dataNascimento": "1990-01-01"
}

### Search authors
# @name searchAuthor
GET {{baseUrl}}/autores?nome=adsljfdoas;
Content-Type: application/json


### Delete Author
# @name deleteAuthor
DELETE  {{baseUrl}}/autores/{{authorId}}
Content-Type: application/json


# Livros 

### Create a new Book
# @name createBook
POST {{baseUrl}}/livros
Content-Type: application/json
Authorization: Basic gus:123123123

{
    "isbn": "978-0974192581",
    "genero": "POESIA",
    "dataPublicacao": "2019-01-01",
    "preco": null,
    "titulo": "1",
    "autorId": "{{authorId}}"
}

### Get the response.id from the previous request
# @name getBook
GET {{baseUrl}}/livros/ea43cccc-f141-4b25-af22-c050b3ee1e5a
Content-Type: application/json

### DELETE BOOK
# @name deleteBook
DELETE {{baseUrl}}/livros/ea43cccc-f141-4b25-af22-c050b3ee1e5a
Content-Type: application/json


### Search
# @name search
GET {{baseUrl}}/livros?isbn=978-0974192581&nome-autor&genero&ano-publicacao
# Authorization: Basic user:cc99e988-e004-40ee-8c15-5d9e10685d15 
Authorization: Basic aaa:123123123
# above basic authentication
Content-Type: application/json

### update Author
# @name updateBook
PUT {{baseUrl}}/livros/ea43cccc-f141-4b25-af22-c050b3ee1e5a
Content-Type: application/json

{
    "titulo": "pumpkin",
}
