@baseUrl=http://localhost:8080

### Create a new Author
# @name createAuthor
POST {{baseUrl}}/autores
Content-Type: application/json

{
    "nome": "12313",
    "nacionalidade": "1232133",
    "dataNascimento": "2020-01-01"
}

@authorId = {{createAuthor.response.body.id}}

### Get the response.id from the previous request
# @name getAuthor
GET {{baseUrl}}/autores/{{authorId}}
Content-Type: application/json

### update Author
# @name updateAuthor
PUT {{baseUrl}}/autores/{{authorId}}
Content-Type: application/json

{
    "nome": "ggggg a",
    "nacionalidade": "asdfasdf",
    "dataNascimento": "1990-01-01"
}

### Search authors
# @name searchAuthor
GET {{baseUrl}}/autores?nome=adsljfdoas;
Content-Type: application/json


### Delete Author
# @name deleteAuthor
DELETE  {{baseUrl}}/autores/{{authorId}}
Content-Type: application/json


# Livros 

### Create a new Book
# @name createBook
POST {{baseUrl}}/livros
Content-Type: application/json

{
    "isbn": "978-0974192581",
    "genero": "POESIA",
    "titulo": "1",
    "autorId": "{{authorId}}"
}

### Get the response.id from the previous request
# @name getBook
GET {{baseUrl}}/livros/668facf8-d17c-4cc5-9e80-84d7851e13a9
Content-Type: application/json
