management:
    server:
        port: 9001
    endpoints:
        web:
            exposure:
                include: "*" #beans, logfile....
                
spring:
    output:
        ansi:
            enabled: always
    application:
        name: libraryapi
    profiles:
        active: production
    
# none, create-drop para mapear 