spring:
    application:
        name: libraryapi
    datasource:
        url: jdbc:postgresql://localhost:5432/library
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                ddl-auto: update
        hibernate:
            ddl-auto: update
# none, create-drop para mapear 