spring:
    security:
        oauth2:
            client:
                registration:
                    google:
                        clientId: 400926382153-5at128a9hqfi04jhdeqcfsb5jgnurg1d.apps.googleusercontent.com
                        clientSecret: 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
                #         scope:
                #             - email
                #             - profile
                # provider:
                #     google:
                #         authorizationUri: https://accounts.google.com/o/oauth2/auth
                #         tokenUri: https://accounts.google.com/o/oauth2/token
                #         userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
                #         userNameAttribute: sub
    application:
        name: libraryapi
    datasource:
        url: jdbc:postgresql://localhost:5432/library
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                ddl-auto: update
        hibernate:
            ddl-auto: update
# none, create-drop para mapear 